name: CI/CD
on:
  push:
  workflow_dispatch:

jobs:

  echo:
    name: Echo
    runs-on: ubuntu-latest
    steps:
      - name: Echo tests
        run: |
          echo "HOLY SHIT"
          echo "pwd: $PWD"
          Echo "pwd: ${PWD}"