name: CI/CD
on:
  push:
  workflow_dispatch:

jobs:

  backend:
    name: Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: setup backend
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run tests
        run: mvn clean install

  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:

      - name: checkout frontend
        uses: actions/checkout@v2
        with:
          repository: 'johnshift/simple-frontend'
          
      - name: echo npm & node versions
        run: npm --version && node --version

      - name: setup frontend
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Frontend build + tests
        run: npm install && npm build && npm test
