name: CI/CD
on:
  push:
  workflow_dispatch:

jobs:


  echo:
    name: Echo
    runs-on: ubuntu-latest
    env:
      msg_1: "this is message #1"
    steps:
      - name: Echo tests
        run: |
          echo "HOLY SHIT"
          echo "pwd: $PWD"
          echo "home: $HOME"
          echo "env msg#1: ${{ env.msg_1 }}"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
      - name: clone repo
        uses: actions/checkout@v2
        with:
          repository: 'johnshift/github-actions'
          path: 'my-repo'
        run: |
          echo "ls GITHUB_WORKSPACE: ";ls