name: CI/CD
on:
  push:
  workflow_dispatch:

jobs:

  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:

      - name: install tree
        run: sudo apt install tree -y

      # saved in $GITHUB_WORKSPACE/backend
      - name: checkout backend
        uses: actions/checkout@v2
        with:
          repository: 'johnshift/github-actions'
          path: backend

      # saved in $GITHUB_WORKSPACE/frontend
      - name: checkout frontend
        uses: actions/checkout@v2
        with:
          repository: 'johnshift/simple-frontend'
          path: frontend

      - name: echo workspace before setup
        run: tree -d -L 2 $GITHUB_WORKSPACE

      - run: cd $GITHUB_WORKSPACE/backend
      - name: setup backend
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - run: cd $GITHUB_WORKSPACE/frontend
      - name: setup frontend
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: echo workspace before setup
        run: tree -d -L 2 $GITHUB_WORKSPACE

  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
    
      - run: cd $GITHUB_WORKSPACE/backend
      - name: Backend build + tests
        working-directory: $GITHUB_WORKSPACE/backend
        run: mvn clean install
      
      - run: cd $GITHUB_WORKSPACE/frontend
      - name: Frontend build + tests
        working-directory: $GITHUB_WORKSPACE/frontend
        run: npm build && npm test
