name: CI/CD
on:
  push:
  workflow_dispatch:

jobs:

  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:

      # saved in $GITHUB_WORKSPACE/backend
      - name: checkout backend
        uses: actions/checkout@v2
        with:
          repository: 'johnshift/github-actions'
          path: backend

      # saved in $GITHUB_WORKSPACE/frontend
      - name: checkout frontend
        uses: actions/checkout@v2
        with:
          repository: 'johnshift/simple-frontend'
          path: frontend

  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Backend
        working-directory: $GITHUB_WORKSPACE/backend
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
        run: mvn clean install
      
      - name: Frontend
        working-directory: $GITHUB_WORKSPACE/frontend
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        run: npm build && npm test

